//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VuelosOne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ciudad
    {
        public Ciudad()
        {
            this.Vuelo = new HashSet<Vuelo>();
            this.Vuelo1 = new HashSet<Vuelo>();
        }
    
        public int Codigo { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<Vuelo> Vuelo { get; set; }
        public virtual ICollection<Vuelo> Vuelo1 { get; set; }
    }
}
