//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VuelosOne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public string Codigo { get; set; }
        public int Vuelo { get; set; }
        public int Usuario { get; set; }
    
        public virtual Usuario Usuario1 { get; set; }
        public virtual Vuelo Vuelo1 { get; set; }
    }
}
