//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VuelosOne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Reserva = new HashSet<Reserva>();
        }
    
        public int Codigo { get; set; }
        public string Username { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<Reserva> Reserva { get; set; }
    }
}
