//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VuelosOne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vuelo
    {
        public Vuelo()
        {
            this.Reserva = new HashSet<Reserva>();
        }
    
        public int Id { get; set; }
        public string Estado { get; set; }
        public int AsientosDisponibles { get; set; }
        public System.DateTime HorarioSalida { get; set; }
        public System.DateTime HorarioLlegada { get; set; }
        public int Origen { get; set; }
        public int Destino { get; set; }
        public decimal Tarifa { get; set; }
    
        public virtual Ciudad Ciudad { get; set; }
        public virtual Ciudad Ciudad1 { get; set; }
        public virtual ICollection<Reserva> Reserva { get; set; }
    }
}
